package Frame;

import Banco.ExtractDoc;
import Classes.Campeao;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author guisa
 */
public class Tela extends javax.swing.JFrame {
    static public ArrayList<Campeao> lista;
    static public int[] tiers;
    static public int[] dificuldades;
    Probabilidade prob;
    Sortear sort;
    /**
     * Creates new form Tela
     */
    public Tela(){
        initComponents();
        lista=new ArrayList<Campeao>();
        tiers=new int[6];
        try{
            ExtractDoc.extrairCampeoes();
        }catch(FileNotFoundException exc){
            System.out.println(exc.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBProbabilidade = new javax.swing.JButton();
        jBSortear = new javax.swing.JButton();
        jBInicializar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBProbabilidade.setText("Arrumar Probabilidades");
        jBProbabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProbabilidadeActionPerformed(evt);
            }
        });

        jBSortear.setText("Sortear");
        jBSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSortearActionPerformed(evt);
            }
        });

        jBInicializar.setText("Inicializar");
        jBInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicializarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBProbabilidade)
                .addGap(18, 18, 18)
                .addComponent(jBSortear)
                .addGap(18, 18, 18)
                .addComponent(jBInicializar)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBProbabilidade)
                    .addComponent(jBSortear)
                    .addComponent(jBInicializar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBProbabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProbabilidadeActionPerformed
        if(prob!=null){
            prob.dispose();
        }
        prob=new Probabilidade();
        prob.setVisible(true);
    }//GEN-LAST:event_jBProbabilidadeActionPerformed

    private void jBSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSortearActionPerformed
        if(sort!=null){
            sort.dispose();
        }
        sort=new Sortear(); 
        sort.setVisible(true);
    }//GEN-LAST:event_jBSortearActionPerformed

    private void jBInicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicializarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBInicializarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInicializar;
    private javax.swing.JButton jBProbabilidade;
    private javax.swing.JButton jBSortear;
    // End of variables declaration//GEN-END:variables
}
