/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorvete21.pkg03;


/**
 *
 * @author PC-01
 */
public class frmCalendario extends javax.swing.JFrame {

    /**
     * Creates new form SorveteDeMilho
     */
    public frmCalendario() {
        super("Calendário");
        initComponents();
        setDefaultCloseOperation(2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeDoMes = new javax.swing.JTextField();
        lab4 = new javax.swing.JLabel();
        lab8 = new javax.swing.JLabel();
        lab9 = new javax.swing.JLabel();
        lab11 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab5 = new javax.swing.JLabel();
        lab6 = new javax.swing.JLabel();
        lab7 = new javax.swing.JLabel();
        lab10 = new javax.swing.JLabel();
        lab12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labInfo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(250, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomeDoMes.setEditable(false);
        getContentPane().add(txtNomeDoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, -1));

        lab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab4.setText("   4");
        lab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab4MouseClicked(evt);
            }
        });
        getContentPane().add(lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 30, 20));

        lab8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab8.setText("   8");
        lab8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab8MouseClicked(evt);
            }
        });
        getContentPane().add(lab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 30, 30));

        lab9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab9.setText("   9");
        lab9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab9MouseClicked(evt);
            }
        });
        getContentPane().add(lab9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 30, 30));

        lab11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab11.setText("11");
        lab11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab11MouseClicked(evt);
            }
        });
        getContentPane().add(lab11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 20, 30));

        lab1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab1.setText("  1");
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab1MouseClicked(evt);
            }
        });
        getContentPane().add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 30, 20));

        lab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab2.setText("  2");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab2MouseClicked(evt);
            }
        });
        getContentPane().add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 30, 20));

        lab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab3.setText("3");
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab3MouseClicked(evt);
            }
        });
        getContentPane().add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 20, 20));

        lab5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab5.setText("  5");
        lab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab5MouseClicked(evt);
            }
        });
        getContentPane().add(lab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 30));

        lab6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab6.setText(" 6");
        lab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab6MouseClicked(evt);
            }
        });
        getContentPane().add(lab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 20, 30));

        lab7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab7.setText("   7");
        lab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab7MouseClicked(evt);
            }
        });
        getContentPane().add(lab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 30, 30));

        lab10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lab10.setText("10");
        lab10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab10MouseClicked(evt);
            }
        });
        getContentPane().add(lab10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 20, 30));

        lab12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lab12.setText("12");
        lab12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab12MouseClicked(evt);
            }
        });
        getContentPane().add(lab12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 20, 30));

        jLabel3.setText("Dando Nome Ao Mês");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        labInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorvete21/Imagens/simbolInfo.png"))); // NOI18N
        labInfo.setText("Info");
        labInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labInfoMouseClicked(evt);
            }
        });
        getContentPane().add(labInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorvete21/Imagens/Calendario.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(160, 160));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void lab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseClicked
            txtNomeDoMes.setText("Março");
    }//GEN-LAST:event_lab3MouseClicked
    private void lab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseClicked
        txtNomeDoMes.setText("Janeiro");
    }//GEN-LAST:event_lab1MouseClicked
    private void lab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseClicked
        txtNomeDoMes.setText("Fevereiro");
    }//GEN-LAST:event_lab2MouseClicked
    private void lab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseClicked
        txtNomeDoMes.setText("Abril");
    }//GEN-LAST:event_lab4MouseClicked
    private void lab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab5MouseClicked
        txtNomeDoMes.setText("Maio");
    }//GEN-LAST:event_lab5MouseClicked
    private void lab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab6MouseClicked
        txtNomeDoMes.setText("Junho");
    }//GEN-LAST:event_lab6MouseClicked
    private void lab7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab7MouseClicked
        txtNomeDoMes.setText("Julho");
    }//GEN-LAST:event_lab7MouseClicked
    private void lab8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab8MouseClicked
        txtNomeDoMes.setText("Agosto");
    }//GEN-LAST:event_lab8MouseClicked
    private void lab9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab9MouseClicked
        txtNomeDoMes.setText("Setembro");
    }//GEN-LAST:event_lab9MouseClicked
    private void lab10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab10MouseClicked
        txtNomeDoMes.setText("Outubro");
    }//GEN-LAST:event_lab10MouseClicked
    private void lab11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab11MouseClicked
        txtNomeDoMes.setText("Novembro");
    }//GEN-LAST:event_lab11MouseClicked
    private void lab12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab12MouseClicked
        txtNomeDoMes.setText("Dezembro");
    }//GEN-LAST:event_lab12MouseClicked
    private void labInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labInfoMouseClicked
        new info("Calendario").setVisible(true);
    }//GEN-LAST:event_labInfoMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab10;
    private javax.swing.JLabel lab11;
    private javax.swing.JLabel lab12;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel lab8;
    private javax.swing.JLabel lab9;
    private javax.swing.JLabel labInfo;
    private javax.swing.JTextField txtNomeDoMes;
    // End of variables declaration//GEN-END:variables
}
