/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorvete21.pkg03;

/**
 *
 * @author guisa
 */
public class frmEx3 extends javax.swing.JFrame {

    /**
     * Creates new form frmEx3
     */
    public frmEx3() {
        super("Exercicio 3");
        initComponents();
        setDefaultCloseOperation(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labInfo = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labLimpar = new javax.swing.JLabel();
        labRandomizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorvete21/Imagens/simbolInfo.png"))); // NOI18N
        labInfo.setText("Informação");
        labInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labInfoMouseClicked(evt);
            }
        });

        txtTotal.setEditable(false);

        jLabel1.setText("2º Valor");

        jLabel2.setText("Randomizado:");

        jLabel3.setText("1ºValor");

        labLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorvete21/Imagens/symbolLimpar.png"))); // NOI18N
        labLimpar.setText("Limpar campos");
        labLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labLimparMouseClicked(evt);
            }
        });

        labRandomizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorvete21/Imagens/symbolRandom.png"))); // NOI18N
        labRandomizar.setText("Randomizar");
        labRandomizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labRandomizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValor1)
                            .addComponent(txtValor2)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(labRandomizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labLimpar)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labInfo)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labLimpar)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(labRandomizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void labInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labInfoMouseClicked
        new info("Randomização").setVisible(true);
    }//GEN-LAST:event_labInfoMouseClicked
    private void labLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLimparMouseClicked
        txtValor1.setText(null);
        txtValor2.setText(null);
        txtTotal.setText(null);
    }//GEN-LAST:event_labLimparMouseClicked

    private void labRandomizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labRandomizarMouseClicked
        double valor1 = Double.parseDouble(txtValor1.getText());
        double valor2 = Double.parseDouble(txtValor2.getText());
        double total = 0;
        if (valor1==valor2)
            total = valor1+valor2;
        else if(valor1>valor2)
            total = valor1 - valor2;
        else if(valor2>valor1)
            total = valor1 * valor2;
        
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_labRandomizarMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labInfo;
    private javax.swing.JLabel labLimpar;
    private javax.swing.JLabel labRandomizar;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
