/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Classes.Campeao;
import java.util.Random;
import java.util.ArrayList;

/**
 *
 * @author guisa
 */
public class Sortear extends javax.swing.JFrame {
    /**
     * Creates new form Sortear
     */
    Apresentador apr;
    public Sortear() {
        initComponents();
        apr=null;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTSeiJogar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTDificil = new javax.swing.JTextField();
        jTMedio = new javax.swing.JTextField();
        jTFacil = new javax.swing.JTextField();
        jTFacilimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTroll = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBSortear = new javax.swing.JButton();
        jCLane = new javax.swing.JComboBox<>();
        jRBNotLane = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTSeiJogar.setText("24");
        getContentPane().add(jTSeiJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 30, -1));

        jLabel2.setText("Sei Jogar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, -1, -1));

        jLabel3.setText("Probabilidade");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel4.setText("Tier");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTDificil.setText("10");
        getContentPane().add(jTDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 30, -1));

        jTMedio.setText("35");
        getContentPane().add(jTMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 30, -1));

        jTFacil.setText("20");
        getContentPane().add(jTFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 30, -1));

        jTFacilimo.setText("10");
        getContentPane().add(jTFacilimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 30, -1));

        jLabel5.setText("Díficil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        jLabel6.setText("Médio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));

        jLabel7.setText("Fácil");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        jLabel8.setText("Fácilímo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jTroll.setText("1");
        getContentPane().add(jTroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 30, -1));

        jLabel9.setText("Troll");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));

        jBSortear.setText("Sortear");
        jBSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSortearActionPerformed(evt);
            }
        });
        getContentPane().add(jBSortear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jCLane.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top", "Jg", "Mid", "Adc", "Sup" }));
        getContentPane().add(jCLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, -1, -1));

        jRBNotLane.setText("Não Lane");
        getContentPane().add(jRBNotLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSortearActionPerformed
                Random generator= new Random();
        int soma=0;
        int lane=jCLane.getSelectedIndex();
        ArrayList<Campeao> campeoes=new ArrayList<>();
        if(jRBNotLane.isSelected()){
            for(Campeao campeao : Tela.lista){
                if(campeao.getStatus()[lane]==0){
                    soma+=1;
                    campeoes.add(campeao);  
                    System.out.println("Campeao: "+campeao.getNome());
                }
            }
            int val=(int) (generator.nextDouble()*soma);
            if(apr!=null){
                apr.dispose();
            }
            apr=new Apresentador(campeoes.get(val).getNome());
            apr.setVisible(true);
        }else{
            int dificil=Integer.parseInt(jTDificil.getText());
            int medio=Integer.parseInt(jTMedio.getText());
            int facil=Integer.parseInt(jTFacil.getText());
            int facilimo=Integer.parseInt(jTFacilimo.getText());
            int troll=Integer.parseInt(jTroll.getText());
            int seiJogar=Integer.parseInt(jTSeiJogar.getText());
            int sum=dificil+medio+facil+facilimo+troll+seiJogar;
            Double val=generator.nextDouble()*sum;
            int grupo=0;
            if(val<dificil){
                grupo=1;
            }else if(val<dificil+medio){
                grupo=2;
            }else if(val<dificil+medio+facil){
                grupo=3;
            }else if(val<dificil+medio+facil+facilimo){
                grupo=4;
            }else if(val<dificil+medio+facil+facilimo+troll){
                grupo=6;
            }else{
                grupo=5;
            }
            for(Campeao campeao : Tela.lista){
                if(campeao.getStatus()[lane]==grupo){
                    soma+=Tela.tiers[campeao.getStatus()[lane+5]];
                    campeoes.add(campeao);
                }
            }
            val=generator.nextDouble()*soma;
            System.out.println("gerado: "+val);
            String[] aux_Dificuldade={"Não Existe","Díficil","Médio","Fácil", "Fácilimo", "Sei Jogar", "Troll",""};
            System.out.println("grupo: "+aux_Dificuldade[grupo]);
            for(Campeao campeao:campeoes){
                System.out.println("Campeao: "+campeao.getNome());
                if(val<Tela.tiers[campeao.getStatus()[lane+5]]){
                    if(apr!=null){
                        apr.dispose();
                    }
                    apr=new Apresentador(campeao.getNome());
                    break;
                }
                val-=Tela.tiers[campeao.getStatus()[lane+5]];
            }
            apr.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jBSortearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSortear;
    private javax.swing.JComboBox<String> jCLane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRBNotLane;
    private javax.swing.JTextField jTDificil;
    private javax.swing.JTextField jTFacil;
    private javax.swing.JTextField jTFacilimo;
    private javax.swing.JTextField jTMedio;
    private javax.swing.JTextField jTSeiJogar;
    private javax.swing.JTextField jTroll;
    // End of variables declaration//GEN-END:variables
}
